services:
  idle-game:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_BASE=Emberhill
      # - VITE_HMR_HOSTNAME=localhost
    command: npm run dev -- --host