
// THIS FILE IS AUTO-GENERATED BY compile-gamedata.ts. DO NOT EDIT.

import type {ProgressionData} from "@/shared/types/game.types.ts";

export const PROGRESSION: Record<string, ProgressionData> = {
    warmstone: {
        1: { xp: 0, resources: [], rewards: [{ type: "unlock_building", buildingId: "woodcutter" }, { type: "unlock_building", buildingId: "campfire" }, { type: "unlock_building", buildingId: "foragers_hut" }] },
        2: { xp: 100, resources: [], rewards: [{ type: "unlock_building", buildingId: "mine" }] },
        3: { xp: 150, resources: [{ type: "resource", id: "LOG_OAK", amount: 10 }, { type: "resource", id: "FIBER", amount: 5 }], rewards: [{ type: "unlock_building", buildingId: "workshop" }] }
    },
    farm: {
        1: { xp: 0, resources: [], rewards: [{ type: "unlock_process", processId: "grow_blackberries" }] }
    },
    foragers_hut: {
        1: { xp: 0, resources: [], rewards: [{ type: "unlock_process", processId: "collect_berries" }] },
        2: { xp: 100, resources: [{ type: "resource", id: "BERRIES", amount: 30 }], rewards: [{ type: "unlock_process", processId: "gather_kindling" }] },
        3: { xp: 250, resources: [{ type: "resource", id: "BERRIES", amount: 100 }, { type: "resource", id: "TWIGS", amount: 70 }], rewards: [{ type: "unlock_process", processId: "collect_fibers" }] },
        4: { xp: 450, resources: [{ type: "resource", id: "BLACKBERRY_SEED", amount: 5 }], rewards: [{ type: "unlock_building", buildingId: "farm" }] }
    },
    mine: {
        1: { xp: 0, resources: [], rewards: [{ type: "unlock_process", processId: "mine_stone" }] },
        2: { xp: 100, resources: [{ type: "resource", id: "STONE", amount: 40 }], rewards: [{ type: "unlock_process", processId: "mine_copper_ore" }] }
    },
    woodcutter: {
        1: { xp: 0, resources: [], rewards: [{ type: "unlock_process", processId: "cut_tree_oak" }] },
        2: { xp: 100, resources: [{ type: "resource", id: "LOG_OAK", amount: 20 }], rewards: [{ type: "unlock_process", processId: "cut_tree_birch" }] },
        3: { xp: 500, resources: [{ type: "resource", id: "LOG_OAK", amount: 100 }, { type: "resource", id: "LOG_BIRCH", amount: 100 }], rewards: [{ type: "unlock_process", processId: "cut_tree_pine" }] }
    },
    workshop: {
        1: { xp: 0, resources: [], rewards: [{ type: "unlock_process", processId: "create_crude_hoe" }] }
    }
};
