
// THIS FILE IS AUTO-GENERATED BY compile-gamedata.ts. DO NOT EDIT.

import type {ResourceData} from "@/shared/types/game.types.ts"
import type {ResourceId} from "@/shared/types/resources.types.ts"

// Import all icons
import icon_LOG_OAK from '@/resource-icon/log_oak.png';
import icon_LOG_BIRCH from '@/resource-icon/log_birch.png';
import icon_LOG_PINE from '@/resource-icon/log_pine.png';
import icon_LOG_MAPLE from '@/resource-icon/log_maple.png';
import icon_RESIN from '@/resource-icon/blackberry.png';
import icon_STONE from '@/resource-icon/placeholder.png';
import icon_ORE_COPPER from '@/resource-icon/placeholder.png';
import icon_BERRIES from '@/resource-icon/berries.png';
import icon_TWIGS from '@/resource-icon/branch.png';
import icon_FIBER from '@/resource-icon/hemp.png';
import icon_WEED_SEED from '@/resource-icon/weed.png';
import icon_BLACKBERRY_SEED from '@/resource-icon/blackberry.png';
import icon_GRAIN_SEED from '@/resource-icon/malt.png';
import icon_TILLED_EARTH from '@/resource-icon/soil.png';
import icon_CRUDE_HOE from '@/resource-icon/hoe.png';

export const RESOURCES: Record<ResourceId, ResourceData> = {
    LOG_OAK: {id: 'LOG_OAK',name: 'Oak Log 222',description: `A sturdy, common log from an oak tree. The reliable heartwood of the forest.`,icon: icon_LOG_OAK},
    LOG_BIRCH: {id: 'LOG_BIRCH',name: 'Birch Log',description: `A light, pale log from a slender birch. Its bark is as useful as its wood.`,icon: icon_LOG_BIRCH},
    LOG_PINE: {id: 'LOG_PINE',name: 'Pine Log',description: `A fragrant softwood log, sticky to the touch with fresh resin.`,icon: icon_LOG_PINE},
    LOG_MAPLE: {id: 'LOG_MAPLE',name: 'Maple Log',description: `A dense, fine-grained hardwood, prized by carpenters for its strength and beauty.`,icon: icon_LOG_MAPLE},
    RESIN: {id: 'RESIN',name: 'Tree Resin',description: `A sticky, amber-colored sap from a pine tree. A natural adhesive and waterproofing agent.`,icon: icon_RESIN},
    STONE: {id: 'STONE',name: 'Stone',description: `Stone description`,icon: icon_STONE},
    ORE_COPPER: {id: 'ORE_COPPER',name: 'Copper Ore',description: `Copper Ore description`,icon: icon_ORE_COPPER},
    BERRIES: {id: 'BERRIES',name: 'Berries',description: `A common fruit found throughout the region. While not particularly nourishing, they provide a quick source of energy to stave off the worst of the Hearthstone's decay in the early days.`,icon: icon_BERRIES},
    TWIGS: {id: 'TWIGS',name: 'Twigs',description: `A bundle of dry, brittle twigs, bark, and pinecones. Catches fire far more readily than a whole log. An essential component for starting and maintaining a reliable flame.`,icon: icon_TWIGS},
    FIBER: {id: 'FIBER',name: 'Fiber',description: `Surprisingly strong for a glorified weed`,icon: icon_FIBER},
    WEED_SEED: {id: 'WEED_SEED',name: 'Weed Seed',description: `An unidentifiable seed, gathered from the untamed parts of the world. Planting it is an act of faith. It could yield anything from tough, edible roots and fibrous stalks to, on rare occasions, the ancestors of true grain.`,icon: icon_WEED_SEED},
    BLACKBERRY_SEED: {id: 'BLACKBERRY_SEED',name: 'Blackberry Seed',description: `Domesticate the same thorny bushes you find in the wild. Each seed will grow into a familiar plant that yields a predictable and steady supply of blackberries, removing the uncertainty of foraging.`,icon: icon_BLACKBERRY_SEED},
    GRAIN_SEED: {id: 'GRAIN_SEED',name: 'Grain Seed',description: `A significant agricultural breakthrough. Unlike berries or roots, grain is highly storable and incredibly versatile. Cultivating a steady supply of grain is the first step towards creating a stable food source, brewing valuable ales, and truly domesticating livestock.`,icon: icon_GRAIN_SEED},
    TILLED_EARTH: {id: 'TILLED_EARTH',name: 'Tilled Earth',description: `A plot of land that has been broken up and aerated with a hoe. The soil is now soft and ready to accept a seed. It will revert to packed dirt if left untended for too long`,icon: icon_TILLED_EARTH},
    CRUDE_HOE: {id: 'CRUDE_HOE',name: 'Crude Hoe',description: `A plot of land that has been broken up and aerated with a hoe. The soil is now soft and ready to accept a seed. It will revert to packed dirt if left untended for too long`,icon: icon_CRUDE_HOE}
} as const;
