
// THIS FILE IS AUTO-GENERATED BY compile-gamedata.ts. DO NOT EDIT.

export const AllProcessIds = [
    'burn_log_oak',
    'burn_log_birch',
    'grow_blackberries',
    'till_soil',
    'collect_berries',
    'gather_kindling',
    'collect_fibers',
    'mine_stone',
    'mine_copper_ore',
    'cut_tree_oak',
    'cut_tree_birch',
    'cut_tree_pine',
    'cut_tree_maple',
    'create_crude_hoe'
] as const;
export type ProcessId = typeof AllProcessIds[number];
