
// THIS FILE IS AUTO-GENERATED BY compile-gamedata.ts. DO NOT EDIT.

export const AllProgressionIds = [
    'warmstone',    'farm',    'foragers_hut',    'mine',    'woodcutter',    'workshop'
] as const;
export type ProgressionId = typeof AllProgressionIds[number];
