
// THIS FILE IS AUTO-GENERATED BY compile-gamedata.ts. DO NOT EDIT.

export const AllResourceIds = [
    'LOG_OAK',
    'LOG_BIRCH',
    'LOG_PINE',
    'LOG_MAPLE',
    'RESIN',
    'STONE',
    'ORE_COPPER',
    'BERRIES',
    'TWIGS',
    'FIBER',
    'WEED_SEED',
    'BLACKBERRY_SEED',
    'GRAIN_SEED',
    'TILLED_EARTH',
    'CRUDE_HOE'
] as const;
export type ResourceId = typeof AllResourceIds[number];
