name: Deploy to github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main



jobs:
  deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest

    steps:

          
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Prepare for deploy
        run: |
          npm install
          npm run build
          
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Artifact name
          name: build
          # Path of the directory containing the static assets.
          path: dist
          # Duration after which artifact will expire in days.
          retention-days: 45
